name: Quark签到
on:
  schedule:
    - cron: '0 1 * * *'  # 每天09:00仅一次
  workflow_dispatch:

jobs:
  sign-in:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sleep $((RANDOM % 30))
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install requests
      - name: 执行签到
        env:
          COOKIE_QUARK: ${{ secrets.COOKIE_QUARK }}
          SCKEY: ${{ secrets.SCKEY }}
        run: python checkIn_Quark.py
      - uses: Mattraks/delete-workflow-runs@main
        if: always()
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 60